### ISSUE TITLE
machine.release() or machine.commission() request from python-libmaas causes oops

### ISSUE THREAD

**Issue by artscout** [maas/python-libmaas#252]
Server disconnects every time when machine.release() or machine.commission() called on machine object. regiond has this error when that happens:

2021-02-16 16:33:58 twisted.internet.asyncioreactor.AsyncioSelectorReactor: [critical]
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib/python3/dist-packages/twisted/internet/asyncioreactor.py", line 136, in _readOrWrite
            why = method()
          File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 243, in doRead
            return self._dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 249, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2952, in dataReceived
            return self._channel.dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2245, in dataReceived
            return basic.LineReceiver.dataReceived(self, data)
          File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 579, in dataReceived
            why = self.rawDataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2252, in rawDataReceived
            self._transferDecoder.dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 1699, in dataReceived
            finishCallback(data[contentLength:])
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2115, in _finishRequestBody
            self.allContentReceived()
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2224, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/lib/python3/dist-packages/maasserver/webapp.py", line 54, in requestReceived
            return super().requestReceived(command, path, version)
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 898, in requestReceived
            self.args.update({
          File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 899, in <dictcomp>
            x.encode('iso-8859-1'): \
        builtins.AttributeError: 'NoneType' object has no attribute 'encode'
        
Any ideas?

**Comment by artscout** [comment]
BTW: maas 2.9.2, python-libmaas-0.6.6

**Comment by artscout** [comment]
Update: only happens when API calls going withput any parameters. call machine.commission(wait = False) or machine.release(erase = False) not causing errors.

**Comment by puppetninja** [comment]
I had similar problem after upgrade maas from 2.8.3 to 2.9.2
```
    machine.release()                                                          
  File "/home/windmill/maas-nightwatch/venv/lib/python3.8/site-packages/maas/client/utils/maas_async.py", line 43, in wrapper
    result = eventloop.run_until_complete(result)         
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()                                                     
  File "/home/windmill/maas-nightwatch/venv/lib/python3.8/site-packages/maas/client/viscera/machines.py", line 662, in release
    self._reset(await self._handler.release(**params))    
  File "/home/windmill/maas-nightwatch/venv/lib/python3.8/site-packages/maas/client/bones/__init__.py", line 307, in __call__
    response = await self.bind(**params).call(**data)                   
  File "/home/windmill/maas-nightwatch/venv/lib/python3.8/site-packages/maas/client/bones/__init__.py", line 459, in dispatch
    response = await session.request(                                                                                                                         
  File "/home/windmill/maas-nightwatch/venv/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)                                                                                                                                    
  File "/home/windmill/maas-nightwatch/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/home/windmill/maas-nightwatch/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter                                                                                                                                        
aiohttp.client_exceptions.ServerDisconnectedError    
```
the client environment was not changed, and `machine.release(erase = False)` also works for me

**Comment by djandruczyk** [comment]
This seems to be closely related and/or the same issue I reported https://github.com/maas/python-libmaas/issues/255

**Comment by artscout** [comment]
> This seems to be closely related and/or the same issue I reported #255 except the API calls I'm using: machine.restore_default_configuration(), machine.restore_networking_configuration() don't take arguments at all but it triggers the same fault....

Well it's a lottery for me now, cause release/commission calls with parameters sometimes work, sometimes not. So to MaaS guys,we really need that fixed. I've wrapped that in tries to repeat request till success for now, but that's pretty much dumb solution, nevermind that I've restricted number of retries.

**Comment by sparkiegeek** [comment]
Duplicate of #251
